'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AccountSetting

    '''<summary>
    '''PanelAccountSettingsMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelAccountSettingsMain As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LabelSelectCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelSelectCurrency As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCurrency As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DropDownListCurrencies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListCurrencies As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ButtonSaveChanges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonSaveChanges As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LabelChooseNewPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelChooseNewPassword As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelOldPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelOldPassword As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxOldPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxOldPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LabelNewPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelNewPassword As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxNewPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxNewPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonSavePassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonSavePassword As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LabelCurrentLanguage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCurrentLanguage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DropDownListCurrentLanguage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListCurrentLanguage As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ButtonSaveCurrentLanguage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonSaveCurrentLanguage As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LabelRestrictAutoLoginTimeFrame control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelRestrictAutoLoginTimeFrame As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CheckBoxAutoLoginEnabled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxAutoLoginEnabled As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LabelBoxDateTimePickerAutoAccessTimeLimitsStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelBoxDateTimePickerAutoAccessTimeLimitsStart As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxDateTimePickerAutoAccessTimeLimitsStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxDateTimePickerAutoAccessTimeLimitsStart As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LabelBoxDateTimePickerAutoAccessTimeLimitsEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelBoxDateTimePickerAutoAccessTimeLimitsEnd As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxDateTimePickerAutoAccessTimeLimitsEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxDateTimePickerAutoAccessTimeLimitsEnd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonSaveAutoLoginSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonSaveAutoLoginSettings As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RegularExpressionValidator3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator3 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''DivError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivError As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
