'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Admin

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''LinkButtonMainPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonMainPage As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ImageButtonAdminUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonAdminUsers As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonAdminExceptionsLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonAdminExceptionsLog As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonAdminMainTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonAdminMainTable As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonAdminControlsTranslation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonAdminControlsTranslation As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonAdminCostCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonAdminCostCategories As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonAdminMassEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonAdminMassEmail As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonAdminActionLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonAdminActionLog As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''DivManageUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivManageUsers As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LinkButtonSelectAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonSelectAll As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LinkButtonDeselectAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonDeselectAll As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ButtonShowPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonShowPassword As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ButtonHidePassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonHidePassword As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ButtonSaveUserChanges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonSaveUserChanges As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ButtonDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDelete As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LabelError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridViewUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewUsers As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''DivExceptionsLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivExceptionsLog As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ImageButtonPickRecurrenDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonPickRecurrenDate As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''LabelLogDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLogDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CalendarExceptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExceptions As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''GridViewLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewLog As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''DivMainTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMainTable As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LinkButtonMainTablesGridSelectAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonMainTablesGridSelectAll As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LinkButtonMainTablesGridDeselectAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonMainTablesGridDeselectAll As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''DropDownListMainTableIndex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListMainTableIndex As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DropDownListIDRange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListIDRange As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DropDownListUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListUsers As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DropDownListHasAttachment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListHasAttachment As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ButtonMainTableSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonMainTableSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridViewMainTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewMainTable As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''DivControlsTranslation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivControlsTranslation As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ButtonLangSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonLangSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridViewCurrentLanguage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewCurrentLanguage As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''TextBoxControlID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxControlID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxEN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxEN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxDE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxDE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxBG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxBG As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AddNewTranlation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddNewTranlation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DivCostCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivCostCategories As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TextBoxCategoryID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxCategoryID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxKeyword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxKeyword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonInsertCostCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonInsertCostCategory As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ButtonSaveCostCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonSaveCostCategory As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridViewCostCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewCostCategories As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''DivActionLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivActionLog As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CalendarActionLogStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarActionLogStartDate As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''GridViewUniqueVisitors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewUniqueVisitors As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GridViewActionLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewActionLog As Global.System.Web.UI.WebControls.GridView
End Class
