'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Forms
    
    Partial Public Class BuyStandalone
        
        '''<summary>
        '''ImageButtonDownload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImageButtonDownload As Global.System.Web.UI.WebControls.ImageButton
    End Class
End Namespace
