'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Charts

    '''<summary>
    '''ChartControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChartControl1 As Global.WebChart.ChartControl

    '''<summary>
    '''LabelSum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelSum As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DivError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivError As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LabelExpenses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelExpenses As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridViewAnnualReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewAnnualReport As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ButtonAnnuExpChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAnnuExpChart As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LabelBudget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelBudget As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridViewAnnualReport0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewAnnualReport0 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ButtonAnnuBudgetChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAnnuBudgetChart As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LabelSavings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelSavings As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridViewAnnualReport1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewAnnualReport1 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ButtonAnnuSavingsChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAnnuSavingsChart As Global.System.Web.UI.WebControls.Button
End Class
