'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TestGrid
    
    '''<summary>
    '''HiddenRowID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenRowID As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''HiddenDetailsRowID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenDetailsRowID As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''HiddenDetailsMeasureTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenDetailsMeasureTypeID As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''HiddenSelectedSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenSelectedSupplier As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''HiddenProductID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenProductID As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''HiddenAttachingToDetailsTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenAttachingToDetailsTable As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''HiddenPrintShoppingListDetailsIncludeAllProductEntries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenPrintShoppingListDetailsIncludeAllProductEntries As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''HiddenSumSelectedGridCells control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenSumSelectedGridCells As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''LinkButtonContextMenuCopy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonContextMenuCopy As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LinkButtonContextMenuDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonContextMenuDelete As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LinkButtonContextMenuFlag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonContextMenuFlag As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LinkButtonContextMenuMarkedPaid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonContextMenuMarkedPaid As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LinkButtonContextMenuDownloadAttachment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonContextMenuDownloadAttachment As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LinkButtonContextMenuDeleteAttachment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonContextMenuDeleteAttachment As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LinkButtonContextMenuNextMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonContextMenuNextMonth As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LinkButtonContextMenuPreviousMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonContextMenuPreviousMonth As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LinkButtonContextMenuCopyToNextMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonContextMenuCopyToNextMonth As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LinkButtonContextMenuHidePaid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonContextMenuHidePaid As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ToolkitScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolkitScriptManager1 As Global.AjaxControlToolkit.ToolkitScriptManager
    
    '''<summary>
    '''UpdateProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress
    
    '''<summary>
    '''ToolTip1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolTip1 As Global.MHB.Web.ToolTip
    
    '''<summary>
    '''DivError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivError As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblDuplicateDestinationMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDuplicateDestinationMonth As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''drpDestinationMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpDestinationMonth As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblDuplicateDestinationYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDuplicateDestinationYear As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''drpYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpYear As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblDUplicateFLaggedFilesOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDUplicateFLaggedFilesOnly As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkCopyFlaggedRecordsOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCopyFlaggedRecordsOnly As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDuplicateDeleteAllPriorToCopy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDuplicateDeleteAllPriorToCopy As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkDeleteExistingData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDeleteExistingData As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblCopyAllAsUnpaid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCopyAllAsUnpaid As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkMarkUnpaid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMarkUnpaid As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblZeroActualSums control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblZeroActualSums As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkZeroActualSums control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkZeroActualSums As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ButtonStartDuplicate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonStartDuplicate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''UpdatePanelTabButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelTabButtons As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''PanelTabMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelTabMenu As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Button2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Button3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button3 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Button4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button4 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Button5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button5 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Button6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button6 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Button7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button7 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Button8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button8 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Button9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button9 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Button10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button10 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Button11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button11 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Button12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button12 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DropDownListYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListYear As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''UpdatePanelCurrentMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelCurrentMonth As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''LabelCurrentMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCurrentMonth As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''FileUpload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload1 As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''LabelFileMaxSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelFileMaxSize As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ButtonFileAttachConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonFileAttachConfirm As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonShowAddNewFieldsDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonShowAddNewFieldsDiv As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonUpdate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonDeleteSelectedRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDeleteSelectedRow As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonAddDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAddDetails As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonAttach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAttach As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonSearch As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonUndo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonUndo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonDuplicate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDuplicate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''UpdatePanelButtonHidePaidExpenses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelButtonHidePaidExpenses As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ButtonHidePaidExpenses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonHidePaidExpenses As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LinkButtonSelectAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonSelectAll As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LinkButtonDeselectAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonDeselectAll As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LinkButtonFlagAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonFlagAll As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LinkButtonUnflagAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonUnflagAll As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LabelLastUpdated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLastUpdated As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel5 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''LabelAddNewField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelAddNewField As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxFieldName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxFieldName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''AutoCompleteProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AutoCompleteProducts As Global.AjaxControlToolkit.AutoCompleteExtender
    
    '''<summary>
    '''ListBoxPickCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListBoxPickCategory As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''LabelDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelDescription As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxFieldDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxFieldDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LabelExpectedCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelExpectedCost As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxExpectedValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxExpectedValue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RegularExpressionValidator0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator0 As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''LabelRecurrentBill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelRecurrentBill As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CheckBoxRecurrentExpenditure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxRecurrentExpenditure As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''LabelRecurrentForFollowingMonthsOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelRecurrentForFollowingMonthsOnly As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CheckBoxEnterForEveryMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxEnterForEveryMonth As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''LabelDueDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelDueDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxAddNewReccurentFieldDueDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxAddNewReccurentFieldDueDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CalendarExtender2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender2 As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''LabelEditTableInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelEditTableInfo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RegularExpressionValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator2 As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''ButtonAddField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAddField As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonCloseAddNewDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonCloseAddNewDiv As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''GridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''PanelProgressBarContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelProgressBarContainer As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ImageButtonUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonUp As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ImageButtonDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonDown As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''LabelMoveRows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelMoveRows As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ButtonCalculator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonCalculator As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonAnnualSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAnnualSummary As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonStatistics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonStatistics As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonAnnualReportForExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAnnualReportForExport As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonAnnualSummaryPerCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAnnualSummaryPerCategory As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonNotes As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonEventsCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonEventsCalendar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonProductsManagement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonProductsManagement As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''UpdatePanelTodaySpentList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelTodaySpentList As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''TodaySpentListControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TodaySpentListControl1 As Global.MHB.Web.TodaySpentListControl
    
    '''<summary>
    '''UpdatePanelPurchaseHistoryDateSelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelPurchaseHistoryDateSelector As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''PurchaseHistoryDateSelectorControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PurchaseHistoryDateSelectorControl1 As Global.MHB.Web.PurchaseHistoryDateSelectorControl
    
    '''<summary>
    '''UpdatePanelPurchaseHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelPurchaseHistory As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''PurchaseHistoryControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PurchaseHistoryControl1 As Global.MHB.Web.PurchaseHistoryControl
    
    '''<summary>
    '''UpdatePanelExpectedSum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelExpectedSum As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''LabelCalculationsHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCalculationsHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelExpectedCostSumDifferenceText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelExpectedCostSumDifferenceText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelExpectedCostSumDifference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelExpectedCostSumDifference As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelExpectedCostTotalSumDifferenceText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelExpectedCostTotalSumDifferenceText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelExpectedCostTotalSumDifference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelExpectedCostTotalSumDifference As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelSpentTodayText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelSpentTodayText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LinkButtonSpentToday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonSpentToday As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LinkButtonPurchaseHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonPurchaseHistory As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LabelSumPerDayText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelSumPerDayText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelSumPerDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelSumPerDay As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelExpectedSavingsText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelExpectedSavingsText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelExpectedSavings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelExpectedSavings As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelAllSavingsText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelAllSavingsText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelAllSavings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelAllSavings As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LinkButtonSumFlaggedBillsText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonSumFlaggedBillsText As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblSumFlaggedBillsValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumFlaggedBillsValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelBudgetsHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelBudgetsHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Budget1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Budget1 As Global.MHB.Web.Budgets
    
    '''<summary>
    '''LabelPieChartHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPieChartHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TabContainer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabContainer1 As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''TabPanelCategoriesPieChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelCategoriesPieChart As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''ImageButtonOpenPieChartCategoriesInNewWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonOpenPieChartCategoriesInNewWindow As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ChartCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChartCategories As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''ChartCategoriesPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChartCategoriesPopup As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''TabPanelProductsPieChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelProductsPieChart As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''ImageButtonOpenPieChartProductsInNewWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonOpenPieChartProductsInNewWindow As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ChartProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChartProducts As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''ChartProductsPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChartProductsPopup As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''TabPanelSuppliersPieChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelSuppliersPieChart As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''ImageButtonOpenPieChartSuppliersInNewWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonOpenPieChartSuppliersInNewWindow As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ChartSuppliers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChartSuppliers As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''ChartSuppliersPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChartSuppliersPopup As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''TabPanelMostFrequentlyPurchasedProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelMostFrequentlyPurchasedProducts As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''GridViewMostFrequentlyPurchasedProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewMostFrequentlyPurchasedProducts As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''TabPanelSurplusItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelSurplusItems As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''PanelSurplusItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelSurplusItems As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''GridViewSurplusItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewSurplusItems As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''TabPanelLastEditedItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanelLastEditedItems As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''GridViewLastEditedItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewLastEditedItems As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''UpdatePanelDetailsActionButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelDetailsActionButtons As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ButtonAddExpenditureDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAddExpenditureDetails As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonUpdateDetailsTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonUpdateDetailsTable As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonDeleteFromDetailsTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDeleteFromDetailsTable As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonDetailsTableAttach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDetailsTableAttach As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonDetailsPrintShoppingList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDetailsPrintShoppingList As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonAllDetailsForCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAllDetailsForCategory As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''TextBoxDetailsGridSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxDetailsGridSearch As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DropDownListDetailsPageSizeTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListDetailsPageSizeTop As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''RadioButtonListWeightVolumeSelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonListWeightVolumeSelector As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''UpdatePanelDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelDetails As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''HiddenSelectedLastEditedParentExpenditureTabIndex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenSelectedLastEditedParentExpenditureTabIndex As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''DetailsGridEditedCategoriesTabPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DetailsGridEditedCategoriesTabPanel As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''GridViewDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewDetails As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''GridViewDetailsProductsInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewDetailsProductsInfo As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''UpdatePanelDetailsActionButtonsBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelDetailsActionButtonsBottom As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ButtonDetailsAddBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDetailsAddBottom As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonDetailsSaveBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDetailsSaveBottom As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BittonDetailsDeleteBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BittonDetailsDeleteBottom As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonDetailsTableAttachBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDetailsTableAttachBottom As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonDetailsPrintShoppingListBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDetailsPrintShoppingListBottom As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DropDownListDetailsPageSizeBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListDetailsPageSizeBottom As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''UpdatePanelAjaxFileUploadReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelAjaxFileUploadReceipt As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''AjaxFileUploadReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AjaxFileUploadReceipt As Global.AjaxControlToolkit.AjaxFileUpload
    
    '''<summary>
    '''UpdatePanelDetailsGridChartContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelDetailsGridChartContainer As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''UpdatePanelMoveDetailsSelectParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelMoveDetailsSelectParent As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ListBoxParentExpenditures control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListBoxParentExpenditures As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''UpdatePanelCreateDetailsProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelCreateDetailsProduct As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''LabelNewProductName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelNewProductName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxNewProductName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxNewProductName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LabelNewProductDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelNewProductDescription As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxNewProductDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxNewProductDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LabelNewProductKeywords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelNewProductKeywords As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxNewProductKeywords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxNewProductKeywords As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LabelNewProductListPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelNewProductListPrice As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxNewProductListPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxNewProductListPrice As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RegularExpressionValidator4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator4 As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''LabelNewProductStandardCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelNewProductStandardCost As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxNewProductStandardCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxNewProductStandardCost As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RegularExpressionValidator5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator5 As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''LabelNewProductVolume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelNewProductVolume As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxNewProductVolume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxNewProductVolume As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RegularExpressionValidator6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator6 As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''LabelNewProductWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelNewProductWeight As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxNewProductWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxNewProductWeight As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RegularExpressionValidator7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator7 As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''LabelNewProductSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelNewProductSupplier As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DropDownListNewProductSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListNewProductSupplier As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LabelNewProductCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelNewProductCategory As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DropDownListNewProductCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListNewProductCategory As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ButtonAddNewProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAddNewProduct As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''SupplierSelector1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SupplierSelector1 As Global.MHB.Web.SupplierSelector
    
    '''<summary>
    '''HiddenTextBoxRefreshGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTextBoxRefreshGrid As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''HiddenTextBoxSelectedRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTextBoxSelectedRow As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Note1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Note1 As Global.MHB.Web.Notes
    
    '''<summary>
    '''SearchControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchControl As Global.MHB.Web.SearchControl
    
    '''<summary>
    '''TextBoxControlID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxControlID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBoxCurrentTranslation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxCurrentTranslation As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBoxNewTranslation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxNewTranslation As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ButtonSaveNewTranslation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonSaveNewTranslation As Global.System.Web.UI.WebControls.Button
End Class
