ALTER TABLE tbMainTable01 ADD IsShared BIT NOT NULL DEFAULT 0
ALTER TABLE tbMainTable02 ADD IsShared BIT NOT NULL DEFAULT 0
ALTER TABLE tbMainTable03 ADD IsShared BIT NOT NULL DEFAULT 0
ALTER TABLE tbMainTable04 ADD IsShared BIT NOT NULL DEFAULT 0
ALTER TABLE tbMainTable05 ADD IsShared BIT NOT NULL DEFAULT 0

ALTER TABLE tbDetailsTable01 ADD IsShared BIT NOT NULL DEFAULT 0
ALTER TABLE tbDetailsTable02 ADD IsShared BIT NOT NULL DEFAULT 0
ALTER TABLE tbDetailsTable03 ADD IsShared BIT NOT NULL DEFAULT 0
ALTER TABLE tbDetailsTable04 ADD IsShared BIT NOT NULL DEFAULT 0
ALTER TABLE tbDetailsTable05 ADD IsShared BIT NOT NULL DEFAULT 0
