using System.Collections.Generic;

namespace MHB.BL
{
    public class Enums
    {
        public enum SearchOptions
        {
            SearchBySum = 0,
            SearchByText = 1,
            SearchByDetails = 2,
            AllOfAbove = 3
        }

        public enum SortOptions
        {
            Price = 0,
            Date = 1,
            Category = 2,
        }

        public enum SortDirection
        {
            ASC = 0,
            DESC = 1
        }

        public enum TimeOfDay
        {
            AM = 0,
            PM = 1,
            Undetermined = 2
        }

        public enum MeasureType
        {
            NotSet = 0,
            Weight = 1,
            Volume = 2,
            Count = 3
        }

        public enum Language
        {
            Bulgarian = 0,
            English = 1,
            German = 2
        }

        public enum CurrencyCode
        {
            AED = 0,
            AFN = 1,
            ALL = 2,
            AMD = 3,
            ANG = 4,
            AOA = 5,
            ARS = 6,
            AUD = 7,
            AWG = 8,
            AZN = 9,
            BAM = 10,
            BBD = 11,
            BDT = 12,
            BGN = 13,
            BHD = 14,
            BIF = 15,
            BMD = 16,
            BND = 17,
            BOB = 18,
            BRL = 19,
            BSD = 20,
            BTN = 21,
            BWP = 22,
            BYR = 23,
            BZD = 24,
            CAD = 25,
            CDF = 26,
            CHF = 27,
            CLP = 28,
            CNY = 29,
            COP = 30,
            CRC = 31,
            CUC = 32,
            CUP = 33,
            CVE = 34,
            CZK = 35,
            DJF = 36,
            DKK = 37,
            DOP = 38,
            DZD = 39,
            EGP = 40,
            ERN = 41,
            ETB = 42,
            EUR = 43,
            FJD = 44,
            FKP = 45,
            GBP = 46,
            GEL = 47,
            GGP = 48,
            GHS = 49,
            GIP = 50,
            GMD = 51,
            GNF = 52,
            GTQ = 53,
            GYD = 54,
            HKD = 55,
            HNL = 56,
            HRK = 57,
            HTG = 58,
            HUF = 59,
            IDR = 60,
            ILS = 61,
            IMP = 62,
            INR = 63,
            IQD = 64,
            IRR = 65,
            ISK = 66,
            JEP = 67,
            JMD = 68,
            JOD = 69,
            JPY = 70,
            KES = 71,
            KGS = 72,
            KHR = 73,
            KMF = 74,
            KPW = 75,
            KRW = 76,
            KWD = 77,
            KYD = 78,
            KZT = 79,
            LAK = 80,
            LBP = 81,
            LKR = 82,
            LRD = 83,
            LSL = 84,
            LTL = 85,
            LYD = 86,
            MAD = 87,
            MDL = 88,
            MGA = 89,
            MKD = 90,
            MMK = 91,
            MNT = 92,
            MOP = 93,
            MRO = 94,
            MUR = 95,
            MVR = 96,
            MWK = 97,
            MXN = 98,
            MYR = 99,
            MZN = 100,
            NAD = 101,
            NGN = 102,
            NIO = 103,
            NOK = 104,
            NPR = 105,
            NZD = 106,
            OMR = 107,
            PAB = 108,
            PEN = 109,
            PGK = 110,
            PHP = 111,
            PKR = 112,
            PLN = 113,
            PYG = 114,
            QAR = 115,
            RON = 116,
            RSD = 117,
            RUB = 118,
            RWF = 119,
            SAR = 120,
            SBD = 121,
            SCR = 122,
            SDG = 123,
            SEK = 124,
            SGD = 125,
            SHP = 126,
            SLL = 127,
            SOS = 128,
            SPL = 129,
            SRD = 130,
            STD = 131,
            SVC = 132,
            SYP = 133,
            SZL = 134,
            THB = 135,
            TJS = 136,
            TMT = 137,
            TND = 138,
            TOP = 139,
            TRY = 140,
            TTD = 141,
            TVD = 142,
            TWD = 143,
            TZS = 144,
            UAH = 145,
            UGX = 146,
            USD = 147,
            UYU = 148,
            UZS = 149,
            VEF = 150,
            VND = 151,
            VUV = 152,
            WST = 153,
            XAF = 154,
            XCD = 155,
            XDR = 156,
            XOF = 157,
            XPF = 158,
            YER = 159,
            ZAR = 160,
            ZMW = 161,
            ZWD = 162,
        }

        public static Dictionary<int, Currency> CurrenciesList()
        {
            return new Dictionary<int, Currency>()
            {
                { 0   ,new Currency { ID=0  , Code="AED", Name="United Arab Emirates Dirham"                             }},
                { 1   ,new Currency { ID=1  , Code="AFN", Name="Afghanistan Afghani"                                     }},
                { 2   ,new Currency { ID=2  , Code="ALL", Name="Albania Lek"                                             }},
                { 3   ,new Currency { ID=3  , Code="AMD", Name="Armenia Dram"                                            }},
                { 4   ,new Currency { ID=4  , Code="ANG", Name="Netherlands Antilles Guilder"                            }},
                { 5   ,new Currency { ID=5  , Code="AOA", Name="Angola Kwanza"                                           }},
                { 6   ,new Currency { ID=6  , Code="ARS", Name="Argentina Peso"                                          }},
                { 7   ,new Currency { ID=7  , Code="AUD", Name="Australia Dollar"                                        }},
                { 8   ,new Currency { ID=8  , Code="AWG", Name="Aruba Guilder"                                           }},
                { 9   ,new Currency { ID=9  , Code="AZN", Name="Azerbaijan New Manat"                                    }},
                { 10  ,new Currency { ID=10 , Code="BAM", Name="Bosnia and Herzegovina Convertible Marka"                }},
                { 11  ,new Currency { ID=11 , Code="BBD", Name="Barbados Dollar"                                         }},
                { 12  ,new Currency { ID=12 , Code="BDT", Name="Bangladesh Taka"                                         }},
                { 13  ,new Currency { ID=13 , Code="BGN", Name="Bulgaria Lev"                                            }},
                { 14  ,new Currency { ID=14 , Code="BHD", Name="Bahrain Dinar"                                           }},
                { 15  ,new Currency { ID=15 , Code="BIF", Name="Burundi Franc"                                           }},
                { 16  ,new Currency { ID=16 , Code="BMD", Name="Bermuda Dollar"                                          }},
                { 17  ,new Currency { ID=17 , Code="BND", Name="Brunei Darussalam Dollar"                                }},
                { 18  ,new Currency { ID=18 , Code="BOB", Name="Bolivia Boliviano"                                       }},
                { 19  ,new Currency { ID=19 , Code="BRL", Name="Brazil Real"                                             }},
                { 20  ,new Currency { ID=20 , Code="BSD", Name="Bahamas Dollar"                                          }},
                { 21  ,new Currency { ID=21 , Code="BTN", Name="Bhutan Ngultrum"                                         }},
                { 22  ,new Currency { ID=22 , Code="BWP", Name="Botswana Pula"                                           }},
                { 23  ,new Currency { ID=23 , Code="BYR", Name="Belarus Ruble"                                           }},
                { 24  ,new Currency { ID=24 , Code="BZD", Name="Belize Dollar"                                           }},
                { 25  ,new Currency { ID=25 , Code="CAD", Name="Canada Dollar"                                           }},
                { 26  ,new Currency { ID=26 , Code="CDF", Name="Congo/Kinshasa Franc"                                    }},
                { 27  ,new Currency { ID=27 , Code="CHF", Name="Switzerland Franc"                                       }},
                { 28  ,new Currency { ID=28 , Code="CLP", Name="Chile Peso"                                              }},
                { 29  ,new Currency { ID=29 , Code="CNY", Name="China Yuan Renminbi"                                     }},
                { 30  ,new Currency { ID=30 , Code="COP", Name="Colombia Peso"                                           }},
                { 31  ,new Currency { ID=31 , Code="CRC", Name="Costa Rica Colon"                                        }},
                { 32  ,new Currency { ID=32 , Code="CUC", Name="Cuba Convertible Peso"                                   }},
                { 33  ,new Currency { ID=33 , Code="CUP", Name="Cuba Peso"                                               }},
                { 34  ,new Currency { ID=34 , Code="CVE", Name="Cape Verde Escudo"                                       }},
                { 35  ,new Currency { ID=35 , Code="CZK", Name="Czech Republic Koruna"                                   }},
                { 36  ,new Currency { ID=36 , Code="DJF", Name="Djibouti Franc"                                          }},
                { 37  ,new Currency { ID=37 , Code="DKK", Name="Denmark Krone"                                           }},
                { 38  ,new Currency { ID=38 , Code="DOP", Name="Dominican Republic Peso"                                 }},
                { 39  ,new Currency { ID=39 , Code="DZD", Name="Algeria Dinar"                                           }},
                { 40  ,new Currency { ID=40 , Code="EGP", Name="Egypt Pound"                                             }},
                { 41  ,new Currency { ID=41 , Code="ERN", Name="Eritrea Nakfa"                                           }},
                { 42  ,new Currency { ID=42 , Code="ETB", Name="Ethiopia Birr"                                           }},
                { 43  ,new Currency { ID=43 , Code="EUR", Name="Euro Member Countries"                                   }},
                { 44  ,new Currency { ID=44 , Code="FJD", Name="Fiji Dollar"                                             }},
                { 45  ,new Currency { ID=45 , Code="FKP", Name="Falkland Islands (Malvinas) Pound"                       }},
                { 46  ,new Currency { ID=46 , Code="GBP", Name="United Kingdom Pound"                                    }},
                { 47  ,new Currency { ID=47 , Code="GEL", Name="Georgia Lari"                                            }},
                { 48  ,new Currency { ID=48 , Code="GGP", Name="Guernsey Pound"                                          }},
                { 49  ,new Currency { ID=49 , Code="GHS", Name="Ghana Cedi"                                              }},
                { 50  ,new Currency { ID=50 , Code="GIP", Name="Gibraltar Pound"                                         }},
                { 51  ,new Currency { ID=51 , Code="GMD", Name="Gambia Dalasi"                                           }},
                { 52  ,new Currency { ID=52 , Code="GNF", Name="Guinea Franc"                                            }},
                { 53  ,new Currency { ID=53 , Code="GTQ", Name="Guatemala Quetzal"                                       }},
                { 54  ,new Currency { ID=54 , Code="GYD", Name="Guyana Dollar"                                           }},
                { 55  ,new Currency { ID=55 , Code="HKD", Name="Hong Kong Dollar"                                        }},
                { 56  ,new Currency { ID=56 , Code="HNL", Name="Honduras Lempira"                                        }},
                { 57  ,new Currency { ID=57 , Code="HRK", Name="Croatia Kuna"                                            }},
                { 58  ,new Currency { ID=58 , Code="HTG", Name="Haiti Gourde"                                            }},
                { 59  ,new Currency { ID=59 , Code="HUF", Name="Hungary Forint"                                          }},
                { 60  ,new Currency { ID=60 , Code="IDR", Name="Indonesia Rupiah"                                        }},
                { 61  ,new Currency { ID=61 , Code="ILS", Name="Israel Shekel"                                           }},
                { 62  ,new Currency { ID=62 , Code="IMP", Name="Isle of Man Pound"                                       }},
                { 63  ,new Currency { ID=63 , Code="INR", Name="India Rupee"                                             }},
                { 64  ,new Currency { ID=64 , Code="IQD", Name="Iraq Dinar"                                              }},
                { 65  ,new Currency { ID=65 , Code="IRR", Name="Iran Rial"                                               }},
                { 66  ,new Currency { ID=66 , Code="ISK", Name="Iceland Krona"                                           }},
                { 67  ,new Currency { ID=67 , Code="JEP", Name="Jersey Pound"                                            }},
                { 68  ,new Currency { ID=68 , Code="JMD", Name="Jamaica Dollar"                                          }},
                { 69  ,new Currency { ID=69 , Code="JOD", Name="Jordan Dinar"                                            }},
                { 70  ,new Currency { ID=70 , Code="JPY", Name="Japan Yen"                                               }},
                { 71  ,new Currency { ID=71 , Code="KES", Name="Kenya Shilling"                                          }},
                { 72  ,new Currency { ID=72 , Code="KGS", Name="Kyrgyzstan Som"                                          }},
                { 73  ,new Currency { ID=73 , Code="KHR", Name="Cambodia Riel"                                           }},
                { 74  ,new Currency { ID=74 , Code="KMF", Name="Comoros Franc"                                           }},
                { 75  ,new Currency { ID=75 , Code="KPW", Name="Korea (North) Won"                                       }},
                { 76  ,new Currency { ID=76 , Code="KRW", Name="Korea (South) Won"                                       }},
                { 77  ,new Currency { ID=77 , Code="KWD", Name="Kuwait Dinar"                                            }},
                { 78  ,new Currency { ID=78 , Code="KYD", Name="Cayman Islands Dollar"                                   }},
                { 79  ,new Currency { ID=79 , Code="KZT", Name="Kazakhstan Tenge"                                        }},
                { 80  ,new Currency { ID=80 , Code="LAK", Name="Laos Kip"                                                }},
                { 81  ,new Currency { ID=81 , Code="LBP", Name="Lebanon Pound"                                           }},
                { 82  ,new Currency { ID=82 , Code="LKR", Name="Sri Lanka Rupee"                                         }},
                { 83  ,new Currency { ID=83 , Code="LRD", Name="Liberia Dollar"                                          }},
                { 84  ,new Currency { ID=84 , Code="LSL", Name="Lesotho Loti"                                            }},
                { 85  ,new Currency { ID=85 , Code="LTL", Name="Lithuania Litas"                                         }},
                { 86  ,new Currency { ID=86 , Code="LYD", Name="Libya Dinar"                                             }},
                { 87  ,new Currency { ID=87 , Code="MAD", Name="Morocco Dirham"                                          }},
                { 88  ,new Currency { ID=88 , Code="MDL", Name="Moldova Leu"                                             }},
                { 89  ,new Currency { ID=89 , Code="MGA", Name="Madagascar Ariary"                                       }},
                { 90  ,new Currency { ID=90 , Code="MKD", Name="Macedonia Denar"                                         }},
                { 91  ,new Currency { ID=91 , Code="MMK", Name="Myanmar (Burma) Kyat"                                    }},
                { 92  ,new Currency { ID=92 , Code="MNT", Name="Mongolia Tughrik"                                        }},
                { 93  ,new Currency { ID=93 , Code="MOP", Name="Macau Pataca"                                            }},
                { 94  ,new Currency { ID=94 , Code="MRO", Name="Mauritania Ouguiya"                                      }},
                { 95  ,new Currency { ID=95 , Code="MUR", Name="Mauritius Rupee"                                         }},
                { 96  ,new Currency { ID=96 , Code="MVR", Name="Maldives (Maldive Islands) Rufiyaa"                      }},
                { 97  ,new Currency { ID=97 , Code="MWK", Name="Malawi Kwacha"                                           }},
                { 98  ,new Currency { ID=98 , Code="MXN", Name="Mexico Peso"                                             }},
                { 99  ,new Currency { ID=99 , Code="MYR", Name="Malaysia Ringgit"                                        }},
                { 100 ,new Currency { ID=100, Code="MZN", Name="Mozambique Metical"                                      }},
                { 101 ,new Currency { ID=101, Code="NAD", Name="Namibia Dollar"                                          }},
                { 102 ,new Currency { ID=102, Code="NGN", Name="Nigeria Naira"                                           }},
                { 103 ,new Currency { ID=103, Code="NIO", Name="Nicaragua Cordoba"                                       }},
                { 104 ,new Currency { ID=104, Code="NOK", Name="Norway Krone"                                            }},
                { 105 ,new Currency { ID=105, Code="NPR", Name="Nepal Rupee"                                             }},
                { 106 ,new Currency { ID=106, Code="NZD", Name="New Zealand Dollar"                                      }},
                { 107 ,new Currency { ID=107, Code="OMR", Name="Oman Rial"                                               }},
                { 108 ,new Currency { ID=108, Code="PAB", Name="Panama Balboa"                                           }},
                { 109 ,new Currency { ID=109, Code="PEN", Name="Peru Nuevo Sol"                                          }},
                { 110 ,new Currency { ID=110, Code="PGK", Name="Papua New Guinea Kina"                                   }},
                { 111 ,new Currency { ID=111, Code="PHP", Name="Philippines Peso"                                        }},
                { 112 ,new Currency { ID=112, Code="PKR", Name="Pakistan Rupee"                                          }},
                { 113 ,new Currency { ID=113, Code="PLN", Name="Poland Zloty"                                            }},
                { 114 ,new Currency { ID=114, Code="PYG", Name="Paraguay Guarani"                                        }},
                { 115 ,new Currency { ID=115, Code="QAR", Name="Qatar Riyal"                                             }},
                { 116 ,new Currency { ID=116, Code="RON", Name="Romania New Leu"                                         }},
                { 117 ,new Currency { ID=117, Code="RSD", Name="Serbia Dinar"                                            }},
                { 118 ,new Currency { ID=118, Code="RUB", Name="Russia Ruble"                                            }},
                { 119 ,new Currency { ID=119, Code="RWF", Name="Rwanda Franc"                                            }},
                { 120 ,new Currency { ID=120, Code="SAR", Name="Saudi Arabia Riyal"                                      }},
                { 121 ,new Currency { ID=121, Code="SBD", Name="Solomon Islands Dollar"                                  }},
                { 122 ,new Currency { ID=122, Code="SCR", Name="Seychelles Rupee"                                        }},
                { 123 ,new Currency { ID=123, Code="SDG", Name="Sudan Pound"                                             }},
                { 124 ,new Currency { ID=124, Code="SEK", Name="Sweden Krona"                                            }},
                { 125 ,new Currency { ID=125, Code="SGD", Name="Singapore Dollar"                                        }},
                { 126 ,new Currency { ID=126, Code="SHP", Name="Saint Helena Pound"                                      }},
                { 127 ,new Currency { ID=127, Code="SLL", Name="Sierra Leone Leone"                                      }},
                { 128 ,new Currency { ID=128, Code="SOS", Name="Somalia Shilling"                                        }},
                { 129 ,new Currency { ID=129, Code="SPL", Name="Seborga Luigino"                                         }},
                { 130 ,new Currency { ID=130, Code="SRD", Name="Suriname Dollar"                                         }},
                { 131 ,new Currency { ID=131, Code="STD", Name="Sao Tome and Principe Dobra"                             }},
                { 132 ,new Currency { ID=132, Code="SVC", Name="El Salvador Colon"                                       }},
                { 133 ,new Currency { ID=133, Code="SYP", Name="Syria Pound"                                             }},
                { 134 ,new Currency { ID=134, Code="SZL", Name="Swaziland Lilangeni"                                     }},
                { 135 ,new Currency { ID=135, Code="THB", Name="Thailand Baht"                                           }},
                { 136 ,new Currency { ID=136, Code="TJS", Name="Tajikistan Somoni"                                       }},
                { 137 ,new Currency { ID=137, Code="TMT", Name="Turkmenistan Manat"                                      }},
                { 138 ,new Currency { ID=138, Code="TND", Name="Tunisia Dinar"                                           }},
                { 139 ,new Currency { ID=139, Code="TOP", Name="Tonga Pa'anga"                                           }},
                { 140 ,new Currency { ID=140, Code="TRY", Name="Turkey Lira"                                             }},
                { 141 ,new Currency { ID=141, Code="TTD", Name="Trinidad and Tobago Dollar"                              }},
                { 142 ,new Currency { ID=142, Code="TVD", Name="Tuvalu Dollar"                                           }},
                { 143 ,new Currency { ID=143, Code="TWD", Name="Taiwan New Dollar"                                       }},
                { 144 ,new Currency { ID=144, Code="TZS", Name="Tanzania Shilling"                                       }},
                { 145 ,new Currency { ID=145, Code="UAH", Name="Ukraine Hryvnia"                                         }},
                { 146 ,new Currency { ID=146, Code="UGX", Name="Uganda Shilling"                                         }},
                { 147 ,new Currency { ID=147, Code="USD", Name="United States Dollar"                                    }},
                { 148 ,new Currency { ID=148, Code="UYU", Name="Uruguay Peso"                                            }},
                { 149 ,new Currency { ID=149, Code="UZS", Name="Uzbekistan Som"                                          }},
                { 150 ,new Currency { ID=150, Code="VEF", Name="Venezuela Bolivar"                                       }},
                { 151 ,new Currency { ID=151, Code="VND", Name="Viet Nam Dong"                                           }},
                { 152 ,new Currency { ID=152, Code="VUV", Name="Vanuatu Vatu"                                            }},
                { 153 ,new Currency { ID=153, Code="WST", Name="Samoa Tala"                                              }},
                { 154 ,new Currency { ID=154, Code="XAF", Name="Communaute Financiere Africaine (BEAC) CFA Franc BEAC"   }},
                { 155 ,new Currency { ID=155, Code="XCD", Name="East Caribbean Dollar"                                   }},
                { 156 ,new Currency { ID=156, Code="XDR", Name="International Monetary Fund (IMF) Special Drawing Rights"}},
                { 157 ,new Currency { ID=157, Code="XOF", Name="Communaute Financiere Africaine (BCEAO) Franc"           }},
                { 158 ,new Currency { ID=158, Code="XPF", Name="Comptoirs Francais du Pacifique (CFP) Franc"             }},
                { 159 ,new Currency { ID=159, Code="YER", Name="Yemen Rial"                                              }},
                { 160 ,new Currency { ID=160, Code="ZAR", Name="South Africa Rand"                                       }},
                { 161 ,new Currency { ID=161, Code="ZMW", Name="Zambia Kwacha"                                           }},
                { 162 ,new Currency { ID=162, Code="ZWD", Name="Zimbabwe Dollar"                                         }}
            };
        }

        public enum Month
        {
            NotSet = 0,
            January = 1,
            February = 2,
            March = 3,
            April = 4,
            May = 5,
            June = 6,
            July = 7,
            August = 8,
            September = 9,
            October = 10,
            November = 11,
            December = 12
        }
    }
}