ALTER TABLE tbDetailsTable01 ADD DetailDateCreated DATETIME NULL
ALTER TABLE tbDetailsTable02 ADD DetailDateCreated DATETIME NULL
ALTER TABLE tbDetailsTable03 ADD DetailDateCreated DATETIME NULL
ALTER TABLE tbDetailsTable04 ADD DetailDateCreated DATETIME NULL
ALTER TABLE tbDetailsTable05 ADD DetailDateCreated DATETIME NULL

ALTER TABLE tbMainTable01 ADD DateRecordCreated DATETIME NULL
ALTER TABLE tbMainTable02 ADD DateRecordCreated DATETIME NULL
ALTER TABLE tbMainTable03 ADD DateRecordCreated DATETIME NULL
ALTER TABLE tbMainTable04 ADD DateRecordCreated DATETIME NULL
ALTER TABLE tbMainTable05 ADD DateRecordCreated DATETIME NULL

ALTER TABLE tbMainTable01 ADD FieldInitialValue MONEY NOT NULL DEFAULT 0
ALTER TABLE tbMainTable02 ADD FieldInitialValue MONEY NOT NULL DEFAULT 0
ALTER TABLE tbMainTable03 ADD FieldInitialValue MONEY NOT NULL DEFAULT 0
ALTER TABLE tbMainTable04 ADD FieldInitialValue MONEY NOT NULL DEFAULT 0
ALTER TABLE tbMainTable05 ADD FieldInitialValue MONEY NOT NULL DEFAULT 0

ALTER TABLE tbDetailsTable01 ADD DetailInitialValue MONEY NOT NULL DEFAULT 0
ALTER TABLE tbDetailsTable02 ADD DetailInitialValue MONEY NOT NULL DEFAULT 0
ALTER TABLE tbDetailsTable03 ADD DetailInitialValue MONEY NOT NULL DEFAULT 0
ALTER TABLE tbDetailsTable04 ADD DetailInitialValue MONEY NOT NULL DEFAULT 0
ALTER TABLE tbDetailsTable05 ADD DetailInitialValue MONEY NOT NULL DEFAULT 0

ALTER TABLE tbMainTableTemp ADD DateRecordCreated DATETIME NULL
ALTER TABLE tbMainTableTemp ADD FieldInitialValue MONEY NOT NULL DEFAULT 0





