ALTER TABLE tbProducts ADD OcrKeyWords NVARCHAR(MAX) NOT NULL DEFAULT ''

ALTER TABLE tbDetailsTable01 ADD IsOcrScanned BIT NOT NULL DEFAULT 0
ALTER TABLE tbDetailsTable02 ADD IsOcrScanned BIT NOT NULL DEFAULT 0
ALTER TABLE tbDetailsTable03 ADD IsOcrScanned BIT NOT NULL DEFAULT 0
ALTER TABLE tbDetailsTable04 ADD IsOcrScanned BIT NOT NULL DEFAULT 0
ALTER TABLE tbDetailsTable05 ADD IsOcrScanned BIT NOT NULL DEFAULT 0
