ALTER TABLE dbo.tbMainTable01 ADD IsDeleted BIT NOT NULL DEFAULT 0
ALTER TABLE dbo.tbMainTable02 ADD IsDeleted BIT NOT NULL DEFAULT 0
ALTER TABLE dbo.tbMainTable03 ADD IsDeleted BIT NOT NULL DEFAULT 0
ALTER TABLE dbo.tbMainTable04 ADD IsDeleted BIT NOT NULL DEFAULT 0
ALTER TABLE dbo.tbMainTable05 ADD IsDeleted BIT NOT NULL DEFAULT 0

ALTER TABLE dbo.tbDetailsTable01 ADD IsDeleted BIT NOT NULL DEFAULT 0
ALTER TABLE dbo.tbDetailsTable02 ADD IsDeleted BIT NOT NULL DEFAULT 0
ALTER TABLE dbo.tbDetailsTable03 ADD IsDeleted BIT NOT NULL DEFAULT 0
ALTER TABLE dbo.tbDetailsTable04 ADD IsDeleted BIT NOT NULL DEFAULT 0
ALTER TABLE dbo.tbDetailsTable05 ADD IsDeleted BIT NOT NULL DEFAULT 0