ALTER TABLE dbo.tbMainTable01 ADD FieldOldValue MONEY NOT NULL DEFAULT 0
ALTER TABLE dbo.tbMainTable02 ADD FieldOldValue MONEY NOT NULL DEFAULT 0
ALTER TABLE dbo.tbMainTable03 ADD FieldOldValue MONEY NOT NULL DEFAULT 0
ALTER TABLE dbo.tbMainTable04 ADD FieldOldValue MONEY NOT NULL DEFAULT 0
ALTER TABLE dbo.tbMainTable05 ADD FieldOldValue MONEY NOT NULL DEFAULT 0