CREATE TABLE tbUsersGeoLocationData
(
	ID INT IDENTITY (1,1) NOT NULL, 
	UserID INT NOT NULL DEFAULT 0,
	Ip VARCHAR(40) NOT NULL DEFAULT '',
	CountryCode VARCHAR(5) NOT NULL DEFAULT '',
	CountryName NVARCHAR(200) NOT NULL DEFAULT '',
	RegionCode NVARCHAR(200) NOT NULL DEFAULT '',
	RegionName NVARCHAR(200) NOT NULL DEFAULT '',
	City NVARCHAR(200) NOT NULL DEFAULT '',
	ZipCode NVARCHAR(200) NOT NULL DEFAULT '',
	Latitude FLOAT NOT NULL DEFAULT 0,
	Longitude FLOAT NOT NULL DEFAULT 0,
	LoginDateTime DATETIME NULL
)

ALTER TABLE tbUsersGeoLocationData ADD CONSTRAINT PK_ID PRIMARY KEY (ID)