CREATE TABLE tbProductParameters
(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	ParentID INT NOT NULL,
	ProductID INT FOREIGN KEY REFERENCES tbProducts(ID),
	[Key] NVARCHAR(20) NOT NULL DEFAULT '',
	Value NVARCHAR(MAX) NOT NULL DEFAULT '',	
)