'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MasterPage

    '''<summary>
    '''head control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents head As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''PanelStripMenuLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelStripMenuLinks As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''PanelAdminLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelAdminLinks As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LinkButtonEditMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonEditMode As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LinkButtonAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonAdmin As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LinkButtonHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonHelp As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LinkButtonFAQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonFAQ As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LinkButtonPhorum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonPhorum As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LinkButtonAccountSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonAccountSettings As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LinkButtonSignOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonSignOut As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LabelUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelUser As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelExchangeRates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelExchangeRates As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PanelNavigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelNavigation As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LinkButtonHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonHome As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LabelChooseCurrentLanguage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelChooseCurrentLanguage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ImageButtonEN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonEN As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonDE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonDE As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonBG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonBG As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ContentPlaceHolder1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentPlaceHolder1 As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''LabelLastUserInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelLastUserInfo As Global.System.Web.UI.WebControls.Label
End Class
