'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Budgets

    '''<summary>
    '''lnkShowAddNewIncomePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkShowAddNewIncomePanel As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlAddNewIncome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAddNewIncome As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblNewIncomeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewIncomeName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNewIncomeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewIncomeName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblNewIncomeValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewIncomeValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNewIncomeValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewIncomeValue As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RegularExpressionValidator0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator0 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lblNewIncomeDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewIncomeDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNewIncomeDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewIncomeDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderIncomeDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderIncomeDate As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''RegularExpressionValidatorDueDateGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidatorDueDateGrid As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''btnAddNewIncome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddNewIncome As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelAddNewIncome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelAddNewIncome As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridViewBudgets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewBudgets As Global.System.Web.UI.WebControls.GridView
End Class
