'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CategoryIcons

    '''<summary>
    '''LabelSelectIconRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelSelectIconRepeater As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RepeaterIcons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RepeaterIcons As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''LabelUserIcons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelUserIcons As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RepeaterUserIcons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RepeaterUserIcons As Global.System.Web.UI.WebControls.Repeater
End Class
