'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CategoriesManagement

    '''<summary>
    '''LabelAddNewCategoryHeaderText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelAddNewCategoryHeaderText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelCategoryName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCategoryName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxCategoryName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxCategoryName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LabelCategoryKeywords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCategoryKeywords As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxCategoryKeywords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxCategoryKeywords As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trUploadIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trUploadIcon As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''LabelUploadIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelUploadIcon As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FileUploadIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUploadIcon As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''LabelCategoryAllowedIconFormats control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCategoryAllowedIconFormats As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trSelectIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trSelectIcon As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''LabelSelectedIconText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelSelectedIconText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ImageSelectedIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageSelectedIcon As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LabelSelectedIconFileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelSelectedIconFileName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LinkButtonUploadIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonUploadIcon As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LabelIsPayIconVisible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelIsPayIconVisible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CheckBoxIsPayIconVisible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxIsPayIconVisible As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LabelShareNewCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelShareNewCategory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CheckBoxIsShared control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxIsShared As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ButtonUserDefinedCategorySave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonUserDefinedCategorySave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ButtonUserDefinedCategoryClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonUserDefinedCategoryClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ButtonUserDefinedCategoryBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonUserDefinedCategoryBack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CategoryIcons1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CategoryIcons1 As Global.MHB.Web.CategoryIcons

    '''<summary>
    '''LabelCategoriesList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCategoriesList As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''GridViewCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewCategories As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''LabelUsersCategoriesList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelUsersCategoriesList As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelUsersCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelUsersCategories As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''GridViewUsersCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewUsersCategories As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''UpdatePanelComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelComments As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''GridViewComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewComments As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''LabelName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxAddNewCategoryCommentName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxAddNewCategoryCommentName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LabelNewCategoryComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelNewCategoryComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxAddNewCategoryComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxAddNewCategoryComment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonAddField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAddField As Global.System.Web.UI.WebControls.Button
End Class
