'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProductDetails

    '''<summary>
    '''LabelPDCProductNameText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCProductNameText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCProductName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCProductName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCProductValueText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCProductValueText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCProductValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCProductValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCProductMinValueText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCProductMinValueText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCProductMinValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCProductMinValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LinkButtonPDCProductMinValueDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonPDCProductMinValueDate As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LabelPDCProductMaxValueText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCProductMaxValueText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCProductMaxValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCProductMaxValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LinkButtonPDCProductMaxValueDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonPDCProductMaxValueDate As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LabelPDCProductAvgValueText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCProductAvgValueText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCProductAvgValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCProductAvgValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trAverageConsumption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAverageConsumption As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''LabelPDCAverageConsumptionText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCAverageConsumptionText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCAverageConsumption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCAverageConsumption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCTotalQuantityText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCTotalQuantityText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCTotalQuantityValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCTotalQuantityValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCTotalQuantityPerMonthText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCTotalQuantityPerMonthText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCTotalQuantityPerMonthValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCTotalQuantityPerMonthValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trPackageUnitsCountMonthly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trPackageUnitsCountMonthly As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''LabelPDCTotalPackageUnitsCountText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCTotalPackageUnitsCountText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCTotalPackageUnitsCountValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCTotalPackageUnitsCountValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCTotalSumText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCTotalSumText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCTotalSumValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCTotalSumValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCTotalQuantityYearlyText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCTotalQuantityYearlyText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCTotalQuantityYearlyValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCTotalQuantityYearlyValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCTotalQuantityPerYearText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCTotalQuantityPerYearText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCTotalQuantityPerYearValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCTotalQuantityPerYearValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trPackageUnitsCountYearly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trPackageUnitsCountYearly As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''LabelPDCTotalPackageUnitsCountYearlyText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCTotalPackageUnitsCountYearlyText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCTotalPackageUnitsCountYearlyValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCTotalPackageUnitsCountYearlyValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCTotalSumYearlyText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCTotalSumYearlyText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCTotalSumYearlyValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCTotalSumYearlyValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCAllTimeTotalQtyText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCAllTimeTotalQtyText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCAllTimeTotalQtyValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCAllTimeTotalQtyValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trPackageUnitsCountAllTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trPackageUnitsCountAllTime As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''LabelPDCAllTimeTotalPackageUnitsCountText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCAllTimeTotalPackageUnitsCountText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCAllTimeTotalPackageUnitsCountValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCAllTimeTotalPackageUnitsCountValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCAllTimeTotalSumText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCAllTimeTotalSumText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelPDCAllTimeTotalSumValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPDCAllTimeTotalSumValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridViewProductSupplierInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewProductSupplierInfo As Global.System.Web.UI.WebControls.GridView
End Class
