'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProductsManagement
    
    '''<summary>
    '''UpdateProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress
    
    '''<summary>
    '''UpdatePanelFunctionalControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelFunctionalControls As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''PanelFunctionalControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelFunctionalControls As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ButtonPrintShoppingList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonPrintShoppingList As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LabelFilterByNameText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelFilterByNameText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxFilterByName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxFilterByName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''AutoCompleteProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AutoCompleteProducts As Global.AjaxControlToolkit.AutoCompleteExtender
    
    '''<summary>
    '''LabelFilterByCategoryText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelFilterByCategoryText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DropDownListFilterByCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListFilterByCategory As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LabelFilterBySupplierText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelFilterBySupplierText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DropDownListFilterBySupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListFilterBySupplier As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LabelPageSizeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPageSizeText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DropDownListPageSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListPageSize As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ButtonFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonFilter As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''UpdatePanelProductsList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelProductsList As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''GridViewProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewProducts As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''PanelShoppingListAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelShoppingListAmount As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LabelAddToShoppingListAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelAddToShoppingListAmount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RegularExpressionValidator0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator0 As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''TextBoxAddToShoppingListAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxAddToShoppingListAmount As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ButtonAddToShoppingList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAddToShoppingList As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonCancel As Global.System.Web.UI.WebControls.Button
End Class
