'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SearchControl

    '''<summary>
    '''LabelSearchString control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelSearchString As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxSearchString control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxSearchString As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AutoCompleteSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AutoCompleteSearch As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''LabelSearchBySum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelSearchBySum As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DropDownListHigherOrLowerThan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListHigherOrLowerThan As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TextBoxSum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxSum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RegularExpressionValidator0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator0 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''LabelSelectYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelSelectYear As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DropDownListYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListYear As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CheckBoxSeachByYearToo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxSeachByYearToo As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LabelSearchByCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelSearchByCategory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DropDownListCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListCategory As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CheckBoxSearchByCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxSearchByCategory As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LabelSortBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelSortBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DropDownListSortBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListSortBy As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DropDownListSortDirection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListSortDirection As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RadioButtonListSearchOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonListSearchOptions As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''rliSearchBySum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rliSearchBySum As Global.System.Web.UI.WebControls.ListItem

    '''<summary>
    '''rliSearchByText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rliSearchByText As Global.System.Web.UI.WebControls.ListItem

    '''<summary>
    '''rliSearchByDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rliSearchByDetails As Global.System.Web.UI.WebControls.ListItem

    '''<summary>
    '''rliBoth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rliBoth As Global.System.Web.UI.WebControls.ListItem

    '''<summary>
    '''LabelStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ButtonPerformSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonPerformSearch As Global.System.Web.UI.WebControls.Button
End Class
