'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SuppliersManagement

    '''<summary>
    '''PanelAddNewSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelAddNewSupplier As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LabelNewSupplierName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelNewSupplierName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxNewSupplierName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxNewSupplierName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LabelNewSupplierDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelNewSupplierDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxNewSupplierDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxNewSupplierDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LabelNewSupplierAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelNewSupplierAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxNewSupplierAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxNewSupplierAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LabelNewSupplierPreffered control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelNewSupplierPreffered As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CheckBoxNewSupplierPreffered control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxNewSupplierPreffered As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LabelNewSupplierActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelNewSupplierActive As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CheckBoxNewSupplierActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxNewSupplierActive As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LabelNewSupplierWebsite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelNewSupplierWebsite As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxNewSupplierWebsite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxNewSupplierWebsite As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonCreateNewSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonCreateNewSupplier As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ButtonCreateNewSupplierCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonCreateNewSupplierCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanelSuppliersList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelSuppliersList As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ButtonAddNewSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAddNewSupplier As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridViewSuppliers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewSuppliers As Global.System.Web.UI.WebControls.GridView
End Class
